### ISSUE TITLE
teamID errors in Salaries table for 2014

### ISSUE THREAD

**Issue by apreshill** [cdalzell/Lahman#14] opened 2015-11-03 14:23 UTC
I teach a statistics course and assigned some data wrangling using the Salaries and Teams tables from the Lahman package for a midterm. An astute student pointed out some weirdness in the Salaries table for 2014. There are two extra teamIDs, NYM and SFG, in 2014 (leading to 32 national league teams total for that year). These codes appear to be the franchIDs as opposed to the teamIDs (NYN being the teamID and NYM the franchID; SFN being the teamID and SFG the franchID). But, in 2014, NYN and SFN (the correct teamIDs) also appear, with some salary data present. Code is below. I also pulled the .csv files from Sean Lahman's site and the error is there as well.

```{r}
library(Lahman)
Teams <- Lahman::Teams
Salaries <- Lahman::Salaries
library(dplyr)

# create new payroll dataframe summing over players within teams for each year from Salaries table
payroll <- Salaries %>%
  group_by(yearID, teamID) %>%
  summarise(payroll = sum(salary))

# look at just 2013:2014...
payroll %>% 
  filter(yearID %in% c(2013, 2014)) %>%
  group_by(teamID) %>%
  summarise(n = n()) %>% 
  print(n = 32)

payroll %>%
  filter(yearID %in% c(2013, 2014), teamID %in% c("NYM", "NYN", "SFG", "SFN")) 

# note 32 teams total in NL for 2014: NYM and SFG each appear just in 2014
# by comparison, in the Teams table...
Teams %>% 
  filter(yearID %in% c(2013, 2014), teamID %in% c("NYM", "NYN", "SFG", "SFN")) %>%
  select(yearID:franchID)

# 3 rows for NYN teamID in 2014; 24 for NYM team ID same year
Salaries %>% 
  filter(yearID == 2014, teamID %in% c("NYM", "NYN")) %>%
  group_by(teamID) %>%
  tally()

# 1 row for SFN teamID in 2014; 27 for SFG team ID same year
Salaries %>% 
  filter(yearID == 2014, teamID %in% c("SFG", "SFN")) %>%
  group_by(teamID) %>%
  tally()

# looks like in Salaries table, two franchIDs (NYM and SFG) were mistakenly entered for a few rows instead of the teamID (NYN and SFN)
```

**Comment by djmurphy420** [comment] 2015-11-03 19:59
I can confirm this, both in the Lahman package and in the database. 
library(dplyr)
# Salaries data starts in 1985Salaries <- Lahman::SalariesTeams <- Lahman::Teams %>% filter(yearID >= 1985)
# Summarize the total team salaries and number of players paid per yearpayroll <- Salaries %>% group_by(yearID, teamID) %>%                      summarise(n = n(), teamSalary = sum(salary)) 
# Count the number of teams per year - there are indeed 32 in 2014nTeams <- payroll %>% count(yearID) 
# Filter out 2014 data and teams starting with N or Spayroll %>% filter(yearID == 2014 & teamID %in% grep("^[NS]", .$teamID, value = TRUE))
# The four players affected:Salaries %>% filter(yearID == 2014 & teamID %in% c("NYN", "SFN"))
# By contrast, the teams data only shows 30 teams represented in 2014Teams %>% group_by(yearID) %>% summarise(n = n()) %>% tail(.)tail(nTeams)

Since this anomaly occurs in the Lahman database, Sean should be notified (again :). Thanks to Alison and her students for the reproducible code.
Dennis
 


     On Tuesday, November 3, 2015 6:23 AM, Alison Presmanes Hill <notifications@github.com> wrote:
   

 I teach a statistics course and assigned some data wrangling using the Salaries and Teams tables from the Lahman package for a midterm. An astute student pointed out some weirdness in the Salaries table for 2014. There are two extra teamIDs, NYM and SFG, in 2014 (leading to 32 national league teams total for that year). These codes appear to be the franchIDs as opposed to the teamIDs (NYN being the teamID and NYM the franchID; SFN being the teamID and SFG the franchID). But, in 2014, NYN and SFN (the correct teamIDs) also appear, with some salary data present. Code is below. I also pulled the .csv files from Sean Lahman's site and the error is there as well.library(Lahman)
Teams <- Lahman::Teams
Salaries <- Lahman::Salaries
library(dplyr)

# create new payroll dataframe summing over players within teams for each year from Salaries table
payroll <- Salaries %>%
  group_by(yearID, teamID) %>%
  summarise(payroll = sum(salary))

# look at just 2013:2014...
payroll %>% 
  filter(yearID %in% c(2013, 2014)) %>%
  group_by(teamID) %>%
  summarise(n = n()) %>% 
  print(n = 32)

payroll %>%
  filter(yearID %in% c(2013, 2014), teamID %in% c("NYM", "NYN", "SFG", "SFN")) 

# note 32 teams total in NL for 2014: NYM and SFG each appear just in 2014
# by comparison, in the Teams table...
Teams %>% 
  filter(yearID %in% c(2013, 2014), teamID %in% c("NYM", "NYN", "SFG", "SFN")) %>%
  select(yearID:franchID)

# 3 rows for NYN teamID in 2014; 24 for NYM team ID same year
Salaries %>% 
  filter(yearID == 2014, teamID %in% c("NYM", "NYN")) %>%
  group_by(teamID) %>%
  tally()

# 1 row for SFN teamID in 2014; 27 for SFG team ID same year
Salaries %>% 
  filter(yearID == 2014, teamID %in% c("SFG", "SFN")) %>%
  group_by(teamID) %>%
  tally()

# looks like in Salaries table, two franchIDs (NYM and SFG) were mistakenly entered for a few rows instead of the teamID (NYN and SFN)—

**Comment by beanumber** [comment] 2015-11-03 22:00
@seanlahman

**Comment by friendly** [comment] 2015-11-03 22:58
OK -- these analyses convince me of the value of the Lahman package for this **extra** use of finding such inconsistencies or errors in the original tables.

However, given that we are just trying to reflect the current state of the most recent release by Sean, I don't think we should try to fix these problems.

Rather, it would probably be most useful to create some files to document these problems, perhaps under `inst/problems`

**Comment by seanlahman** [comment] 2015-11-03 23:47
That would be helpful for me, and then I get get the fixes made upstream.
--Sean

---
Sean Lahman
http://seanlahman.com

Follow me on Twitter @SeanLahman

**Comment by djmurphy420** [comment] 2015-11-04 01:00
Re Michael's suggestion, I think it's a sound one that would make it easier for the original database developers to access for the next version. OTOH, the two problems that have arisen in the past month or so have pointed up the need for a system like Michael suggested. I'm glad that Sean has chimed in, so that we know the original developers are aware of, and listening to, problems. Now that we have communication on both sides and an apparently agreed-upon mechanism for reporting issues sent to this repository, let's do it, recognizing that the proposed directory is for issues relating to the original database per se, not to anything we may have created in the R package, which is our sole responsibility.
Dennis 


     On Tuesday, November 3, 2015 3:47 PM, Sean Lahman <notifications@github.com> wrote:
   

 That would be helpful for me, and then I get get the fixes made upstream.
--Sean

---
Sean Lahman
http://seanlahman.com

Follow me on Twitter @SeanLahman

**Comment by seanlahman** [comment] 2016-03-02 14:48
This issue is fixed in the February 2016 release of the Lahman database.  Thanks again for bringing it to my attention.

**Comment by MonkmanMH** [comment] 2016-03-02 15:25
Thanks for your attention to these things, Sean.  Issue now closed.

**Closed by MonkmanMH** 2016-03-02 15:25 UTC
